Feature: Solitaire Chess Solver

  Position:

  4|n|_|_|_|
  3|_|b|_|_|
  2|p|_|_|_|
  1|_|_|_|_|
  a b c d

  ...has a solution: a2-b3 b3-a4

  Scenario Outline: FEN to Solution
    Given a fen of "<fen>"
    When I setup the board
    And I search for the solution
    Then the resulting solution should be "<solution>"
    Examples:
      | puzzle     | fen               | solution                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | Beginner 1 | n3/1b2/p3/4       | a2-b3 b3-a4                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | Beginner 2 | 1n2/2b1/r3/4      | b4-a2 a2-c3                                                                                                                                                                                                                                                                                                                                                                                                                                  |
      | Beginner 3 | 3r/n1p1/4/n2p     | d4-d1 d1-a1 a1-a3 a3-c3                                                                                                                                                                                                                                                                                                                                                                                                                      |
      | Beginner 4 | 4/1rp1/pr2/4      | a2-b3 b2-b3 b3-c3                                                                                                                                                                                                                                                                                                                                                                                                                            |
      | Expert 46  | 1n1b/4/rr2/n1b1   | b4-a2 b2-a2 d4-a1 a2-a1 a1-c1                                                                                                                                                                                                                                                                                                                                                                                                                |
      | Expert 47  | 3n/2n1/1rrp/pb2   | a1-b2 c2-b2 c3-b1 b1-d2 b2-d2 d2-d4, a1-b2 c3-b1 b1-d2 c2-b2 b2-d2 d2-d4, a1-b2 c3-b1 c2-b2 b1-d2 b2-d2 d2-d4, c3-b1 a1-b2 b1-d2 c2-b2 b2-d2 d2-d4, c3-b1 a1-b2 c2-b2 b1-d2 b2-d2 d2-d4, c3-b1 b1-d2 a1-b2 c2-b2 b2-d2 d2-d4                                                                                                                                                                                                                 |
      | Expert 48  | 1rr1/1b1p/nb2/n3  | d3-c4 b3-c4 b4-b2 c4-a2 b2-a2 a2-a1, d3-c4 b3-c4 c4-a2 b4-b2 b2-a2 a2-a1                                                                                                                                                                                                                                                                                                                                                                     |
      | Expert 49  | 3n/3r/bbn1/rpp1   | a1-a2 c1-b2 a2-b2 b2-c2 d4-c2 b1-c2 c2-d3, a1-a2 c1-b2 a2-b2 d4-c2 b2-c2 b1-c2 c2-d3, a1-a2 c1-b2 d4-c2 a2-b2 b2-c2 b1-c2 c2-d3, a1-a2 d4-c2 c1-b2 a2-b2 b2-c2 b1-c2 c2-d3, c1-b2 a1-a2 a2-b2 b2-c2 d4-c2 b1-c2 c2-d3, c1-b2 a1-a2 a2-b2 d4-c2 b2-c2 b1-c2 c2-d3, c1-b2 a1-a2 d4-c2 a2-b2 b2-c2 b1-c2 c2-d3, c1-b2 d4-c2 a1-a2 a2-b2 b2-c2 b1-c2 c2-d3, d4-c2 a1-a2 c1-b2 a2-b2 b2-c2 b1-c2 c2-d3, d4-c2 c1-b2 a1-a2 a2-b2 b2-c2 b1-c2 c2-d3 |
      | Expert 50  | 1r1p/nr2/1b2/1bn1 | b2-c1 b3-b1 c1-a3 a3-b4 b1-b4 b4-d4, b2-c1 c1-a3 a3-b4 b3-b1 b1-b4 b4-d4, b2-c1 c1-a3 b3-b1 a3-b4 b1-b4 b4-d4                                                                                                                                                                                                                                                                                                                                |
      | Expert 51  | 1bn1/1bp1/1r2/pn2 | b2-b3 b3-c3 c3-c4 c4-b4 b4-b1 b1-a1                                                                                                                                                                                                                                                                                                                                                                                                          |
      | Expert 52  | 3r/bkn1/1r2/pbp1  | b2-b1 a3-c1 b1-a1 a1-c1 c1-c3 b3-c3 c3-d4, b2-b1 b1-a1 a3-c1 a1-c1 c1-c3 b3-c3 c3-d4                                                                                                                                                                                                                                                                                                                                                         |
      | Expert 53  | 2pb/1rr1/pb2/nn2  | c3-c4 c4-d4 b2-d4 b3-b1 d4-a1 b1-a1 a1-a2, c3-c4 c4-d4 b2-d4 d4-a1 b3-b1 b1-a1 a1-a2                                                                                                                                                                                                                                                                                                                                                         |
      | Expert 54  | 2p1/4/nrbp/1rn1   | c1-a2 c2-b1 b2-d2 d2-a2 b1-a2 a2-c4, c2-b1 b2-d2 c1-a2 d2-a2 b1-a2 a2-c4, c2-b1 b2-d2 d2-a2 c1-a2 b1-a2 a2-c4, c2-b1 c1-a2 b2-d2 d2-a2 b1-a2 a2-c4                                                                                                                                                                                                                                                                                           |
      | Expert 55  | 3b/3r/bnn1/ppr1   | a1-b2 c1-c2 d4-b2 c2-b2 b2-b1 a2-b1 b1-d3, a1-b2 d4-b2 c1-c2 c2-b2 b2-b1 a2-b1 b1-d3, c1-c2 a1-b2 d4-b2 c2-b2 b2-b1 a2-b1 b1-d3, c1-c2 d4-b2 a1-b2 c2-b2 b2-b1 a2-b1 b1-d3, d4-b2 a1-b2 c1-c2 c2-b2 b2-b1 a2-b1 b1-d3, d4-b2 c1-c2 a1-b2 c2-b2 b2-b1 a2-b1 b1-d3                                                                                                                                                                             |
      | Expert 56  | n3/bp1b/3n/rrp1   | d2-b3 b1-b3 b3-d3 d3-a3 a3-a4 a4-a1 a1-c1                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Expert 57  | 1rbn/1n1p/3b/pr2  | c4-d3 d3-b1 d4-b3 b3-d2 d2-b1 b4-b1 b1-a1, c4-d3 d4-b3 b3-d2 d2-b1 d3-b1 b4-b1 b1-a1, c4-d3 d4-b3 b3-d2 d3-b1 d2-b1 b4-b1 b1-a1, c4-d3 d4-b3 d3-b1 b3-d2 d2-b1 b4-b1 b1-a1, d4-b3 b3-d2 c4-d3 d2-b1 d3-b1 b4-b1 b1-a1, d4-b3 b3-d2 c4-d3 d3-b1 d2-b1 b4-b1 b1-a1, d4-b3 b3-d2 d2-b1 c4-d3 d3-b1 b4-b1 b1-a1, d4-b3 c4-d3 b3-d2 d2-b1 d3-b1 b4-b1 b1-a1, d4-b3 c4-d3 b3-d2 d3-b1 d2-b1 b4-b1 b1-a1, d4-b3 c4-d3 d3-b1 b3-d2 d2-b1 b4-b1 b1-a1 |
      | Expert 58  | 3p/n3/bprr/nb     | a3-b1 c2-b2 b2-b1 b1-a1 a1-a2 a2-d2 d2-d4, c2-b2 a3-b1 b2-b1 b1-a1 a1-a2 a2-d2 d2-d4                                                                                                                                                                                                                                                                                                                                                         |
      | Expert 59  | 1p2/1rr1/2nn/b1pb | c2-a1 d1-b3 a1-b3 b3-d2 c1-d2 d2-c3 c3-b4                                                                                                                                                                                                                                                                                                                                                                                                    |
      | Expert 60  | 2rp/nbr1/bp2/2n1  | a3-c4 b3-c4 c4-a2 c1-a2 a2-c3 b2-c3 c3-d4                                                                                                                                                                                                                                                                                                                                                                                                    |
